:PROPERTIES:
:ID:       69CE17DF-B52C-4D46-A822-143892CD647B
:END:
#+title: 区间估计
#+filed: Statistics
#+OPTIONS: toc:nil
#+filetags: :statistics:interval_estimation:Users:wangfangyuan:Documents:roam:org_roam:

* Description
设 $X_1,\dots,X_n$ 是从总体中抽出的样本， $\theta$ 的估计区间为 $[\hat{\theta_1}(X_1,\dots,X_n),\hat{\theta_2}(X_1,\dots,X_n)]$ 。
这里有两个要求：
1. $\theta$ 要以很大的可能性落在区间 $[\hat{\theta_1},\hat{\theta_2}]$ 之内，即概率：
$P_{\theta}(\hat{\theta_1}(X_1,\dots,X_n)\leq\theta\leq\hat{\theta_2}(X_1,\dots,X_n))$
要尽可能大。
2. 估计的精度要尽可能高，即要求区间的长度 $\hat{\theta_2}-\hat{\theta_1}$ 尽可能小。

给定一个很小的数 $\alpha>0$ ，如果对参数 $\theta$ 的任何值，上式概率都等于 $1-\alpha$ ，
则称区间估计 $[\hat{\theta_1},\hat{\theta_2}]$ 的置信系数为 $1-\alpha$ 。
区间估计也常称为置信区间。

有时，我们无法证明上式对一切 $\theta$ 都恰好等于 $1-\alpha$ ，但知道它不会小于 $1-\alpha$ ，
则我们称 $1-\alpha$ 是 $[\hat{\theta_1},\hat{\theta_2}]$ 的置信水平。
可知，置信水平不是一个唯一的数，若 $\beta$ 为置信水平，那么小于 $\beta$ 的数也是置信水平，
置信系数是置信水平中的最大值。

*** 枢轴变量法
这个方法的思想是：用已有的统计量去估计未知的参数。
1. 找一个与要估计的参数 $g(\theta)$ 有关的统计量 $T$ ，一般是一个良好的点估计。
2. 设法找出 $T$ 和 $g(\theta)$ 的某一函数 $S$ ，其分布 $F$ 要与 $\theta$ 无关， $S$ 称为枢轴变量。
3. 对任意常数 $a\leq b$ ，不等式 $a\leq S(T,g(\theta))\leq b$ 要能改写成等价形式 $A\leq g(\theta)\leq B$ 。
4. 取分布 $F$ 的上 $\alpha/2$ 分位点 $w_{\alpha/2}$ 和 $1-\alpha/2$ 分位点 $w_{\alpha/2}$ ，则有 $F(w_{\alpha/2})-F(w_{1-\alpha/2})=1-\alpha$ ，因此 $P(w_{1-\alpha/2}\leq S(T,g{\theta})\leq w_{\alpha/2})=1-\alpha$ 。

*** 大样本法
利用极限分布，主要是中心极限定理，建立枢轴变量。
