:PROPERTIES:
:ID:       B65D7CF8-7E35-40F3-B034-B4ECA67FF8CA
:ROAM_REFS: https://www.khanacademy.org/science/physics/torque-angular-momentum/torque-tutorial/a/torque
:END:
#+title: Torque
#+filetags: :math:
#+STARTUP: latexpreview


Torque is a measure of force that can cause an object to rotate about an axis. Just as force is what causes an object to accelerate in linear kinematics, torque is what causes an object to acquire angular acceleration.


The magnitude of the torque vector \(\tau\) for a torque produced by a given force \(F\) is

\begin{equation*}
\tau = F r \sin(\theta)
\end{equation*}

where \(r\) is the length of the moment arm and \(\theta\) is the angle between the force vector and the moment arm.


The direction of the torque vector is found by convention using right hand grip rule.


In rotational kinematics, torque takes the place of _force_ in linear kinematics. There's a direct equivalent to Newton's second law of motion (\(F=ma\)), \(\tau=I \alpha\). \(I\) is the [[id:A2039278-620A-47CB-8735-47BFDE715FF6][Rotational Inertia]], and \(\alpha\) is the angular acceleration.
