name: Generate static org-roam-ui page

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate org-roam-ui page
        uses: ikoamu/publish-org-roam-ui@main
        with:
          org-roam-db-filename: roam.db
          deploy-to-pages: true
